version: '3'

services:
  web:
    image: php:apache
    container_name: PHP-exercise
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    networks:
      - default